version: '3'

services:
  nutch:
    build: .
    container_name: apache_nutch
    volumes:
      - ./data:/opt/nutch/crawl
      - ./conf/nutch-site.xml:/opt/nutch/conf/nutch-site.xml
      - ./conf/regex-urlfilter.txt:/opt/nutch/conf/regex-urlfilter.txt
      - ./urls/seed.txt:/opt/nutch/urls/seed.txt
    environment:
      - NUTCH_HOME=/opt/nutch
    networks:
      - apache
    command: ["tail", "-f", "/dev/null"]  # Dòng này giữ container sống
  
  solr:
    image: solr:8.11.2
    container_name: apache_solr
    ports:
      - "8983:8983"
    networks:
      - apache

  cassandra_db:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - apache
      
networks:
  apache:
